### ISSUE TITLE
How to get a EHost project schema to annotate a corpus of documents?

### ISSUE THREAD

**Issue by jluo41** [Blulab-Utah/VAReadmissionMoonstone#1]
Hi, I am studying how to annotate a corpus of documents with your software Moonstone. However, besides input and output directories specified in `tsl.properties`, I need to assign the item `WorkbenchKnowtatorSchemaFile` with an EHost project schema file (in xml format). However, I can't find such a file throughout the whole project. Could you provide a sample schema file for us to make it work?

**Comment by leenlp** [comment]
Hello,

You’e right; the WorkbenchKnowtatorSchemaFile startup parameter is pointing to an EHost project schema file on the development server.  I am attaching a copy of that file to this email, which you can place on your local computer and adjust the startup parameter accordingly.  It contains a number of references used by EHost, but Moonstone only uses those that define the relevant concepts and properties used in the VA 30-day Readmission project.

If you want to just try out Moonstone on hand-entered sentences to get a feel for how it works, you can unhook the evaluation workbench altogether by setting UseWorkbenchInMoonstone = false.  Then, it won’t even attempt to use the project schema file.

Thanks, and best of luck!

Lee

**Comment by jluo41** [comment]
Hello Lee,

Thanks very much for your quick reply. 

I'm sorry that I can find the attached schema file in your email. Could you please send it again to my email: floydjjluo@gmail.com. 

Also, I have tried to annotate hand-entered sentences in the GUI and it worked very well. We hope to annotate documents in batch for our research, and therefore seek to utilize the corpus annotation function.

Thanks for your great work and help.

Best

**Comment by wwchapman** [comment]
Here it is, I think :)

Wendy

**Comment by wwchapman** [comment]
And a note from Lee (I think you weren't included on the response):

Hello,

You’e right; the WorkbenchKnowtatorSchemaFile startup parameter is pointing
to an EHost project schema file on the development server.  I am attaching
a copy of that file to this email, which you can place on your local
computer and adjust the startup parameter accordingly.  It contains a
number of references used by EHost, but Moonstone only uses those that
define the relevant concepts and properties used in the VA 30-day
Readmission project.

If you want to just try out Moonstone on hand-entered sentences to get a
feel for how it works, you can unhook the evaluation workbench altogether
by setting UseWorkbenchInMoonstone = false.  Then, it won’t even attempt to
use the project schema file.

Thanks, and best of luck!

Lee

**Comment by jluo41** [comment]
Thanks for your comments. I have got the schema file from Lee. It works to annotate a corpus of documents. 

Best,

Junjie

**Comment by wwchapman** [comment]
Great - I'd love to hear how it goes for you.

Wendy
